### ISSUE TITLE
Deserialization fails with null target value

### ISSUE THREAD

**Issue by andreybutko** [jlucansky/Camunda.Api.Client#57]
Hi, I'm trying to use Decision Definition service from your lib, but it fails at final deserialization in method PopulateMember inside VariableValue
`protected virtual bool PopulateMember(string memberName, JsonReader reader, JsonSerializer serializer, object target)`
because `object target` parameter - null and it causes an exception during deserialization here:
```
                if (fieldInfo != null) 
                {
                    reader.Read();
                    fieldInfo.SetValue(target, serializer.Deserialize(reader, fieldInfo.FieldType));
                    return true;
                }
```
with message 

> Newtonsoft.Json.JsonSerializationException: 'Cannot convert null value to Camunda.Api.Client.VariableType. Path 'path-value', line 1, position 39.'

HTTP response returns with status code 200.

Any ideas on how it could be fixed?

**Comment by andreybutko** [comment]
![image](https://user-images.githubusercontent.com/32564756/86345986-f3210380-bc64-11ea-8528-40629a15211c.png)

**Comment by gaensebluemchenritter** [comment]
Hi, to me that rather looks as if the data provided is corrupted. If you look into your Screenshot of your Variables at that time, the {null} you can see there is the ToString() Representation of the target which at that point is of type Camunda.Api.Client.VariableValue

The Type-property is set to Boolean, but the Value-property is null. Which results in the JsonConverter trying to apply a null value to a boolean variable, which in turn fails.

So the question is: where do the variables come from and is there, perhaps, a mistake in the type definition? It could be, because a Boolean may never be null per definition.

**Comment by andreybutko** [comment]
I can't understand why it happens, because HTTP status 200 and there is no place where I cast it to a certain type. Maybe you can explain it. Thank you in advance!

**Comment by andreybutko** [comment]
@gaensebluemchenritter  btw,  `client.DecisionDefinitions.ByKey("key").Evaluate(evaluateDecision)` here is what i want to do.
`evaluateDecision` contains one variable where value - JSON. As result It returns an object with a few fields. 
And this call returns the error mentioned above.

**Comment by andreybutko** [comment]
@gaensebluemchenritter I've got a mistake at DMN engine.
